import setuptools


setuptools.setup(
    name="Flask-API-Framework",
    version="0.0.4",
    keywords="flask api framework",
    description="Flask API Framework",
    long_description="Please see the project links.",
    project_urls={
        "Source": "https://github.com/deristrat/flask-api-framework",
    },
    license="BSD-3-Clause",
    package_dir={"": "src"},
    packages=["flask_api_framework"],
    python_requires=">=3.7",
    install_requires=[
        "flask >= 2.0.0",
        "marshmallow ~= 3.18.0",
    ],
    extras_require={
        "test": [
            "flask-sqlalchemy ~= 3.0.5",
            "marshmallow-sqlalchemy ~= 0.28.0",
            "flask-marshmallow ~= 0.15.0",
            "pytest ~= 8.4.1",
            "pytest-cov ~= 6.2.1",
            "flake8 ~= 7.3.0",
            "flake8-bugbear ~= 24.12.12",
            "black ~= 23.12.1",
            "isort ~= 6.0.1",
            "invoke ~= 2.2.0",
            "tox ~= 4.5.2",
        ],
        "build": [
            "wheel ~= 0.37.1",
            "twine ~= 4.0.0",
        ],
    },
    classifiers=[
        # "Development Status :: 1 - Planning",
        # "Development Status :: 2 - Pre-Alpha",
        "Development Status :: 3 - Alpha",
        # "Development Status :: 4 - Beta",
        # "Development Status :: 5 - Production/Stable",
        # "Development Status :: 6 - Mature",
        # "Development Status :: 7 - Inactive",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3 :: Only",
        "Topic :: Software Development",
        "Intended Audience :: Developers",
        "Framework :: Flask",
    ],
)
